In [2]:
# while loop
## coupouns example
## we are using comma to concatenate two variables. Also we can use + sign after converting it into similar data type

coupouns=10
utilized=0
while utilized<11:
    print('Total coupouns left are', coupouns-utilized)
    utilized=utilized +1
print('No coupouns left now')   


Total coupouns left are 10
Total coupouns left are 9
Total coupouns left are 8
Total coupouns left are 7
Total coupouns left are 6
Total coupouns left are 5
Total coupouns left are 4
Total coupouns left are 3
Total coupouns left are 2
Total coupouns left are 1
Total coupouns left are 0
No coupouns left now


In [3]:
## converting interget to string to make the variable similar in ordr to use + sign
coupouns=10
utilized=0
while utilized<11:
    print('Total coupouns left are'+ str(coupouns-utilized))
    utilized=utilized +1
print('No coupouns left now')   


Total coupouns left are10
Total coupouns left are9
Total coupouns left are8
Total coupouns left are7
Total coupouns left are6
Total coupouns left are5
Total coupouns left are4
Total coupouns left are3
Total coupouns left are2
Total coupouns left are1
Total coupouns left are0
No coupouns left now


In [7]:
marks=input()
if marks<40:
    print('failed')
elif marks > 40 and marks < 70:
          print('average')
else:
          print('Passed')
        
          
         

34


TypeError: '<' not supported between instances of 'str' and 'int'

In [8]:

marks = 90
if marks<40:
    print('Grade 1')
elif marks>40 & marks<70:
    print('Grade 2')
else:
    print('Grade 3')

Grade 2


In [19]:

# if, else example
marks=100
if marks< 40:
    print('failed')
elif marks>40 & marks< 70:
    print('average')
else:
    print('passed')
    


average


In [29]:
marks=56
if marks< 40:
    print('failed')
elif marks>40 & marks< 70:
    print('average')
else:
    print('passed')
    

average


In [23]:
## enter your marks example by giving an input
### in this we have to convert everything to string i..e 40 to match marks(input) as it is string
## check error just above for your reference
marks=str(input('enter your marks:'))
if marks< str('40'):
    print('failed')
elif marks>str('40') & marks< str('70'):
    print('average')
else:
    print('passed')
    
    

enter your marks:34
failed


In [ ]:
### arrays

In [30]:
sales=[2343, 2334, 3434,3433]
profit=[434, 554, 654, 433]

In [32]:
import numpy as np

In [33]:
np.array(sales)  ## coverting into an array

array([2343, 2334, 3434, 3433])

In [34]:
np.array(profit) ## coverting into an array

array([434, 554, 654, 433])

In [35]:
type(sales)

list

In [36]:
type(np.array(sales))

numpy.ndarray

In [37]:
type(profit)

list

In [38]:
type(np.array(profit)) ## data type array

numpy.ndarray

In [39]:
profitratio=np.array(profit)/np.array(sales)

In [40]:
profitratio

array([0.18523261, 0.23736075, 0.19044846, 0.12612875])

In [45]:
profit_array=np.array(profit)  ## assisgning variable 

In [46]:
profit_array*3 ### mutliplied by 3, this will multiply the array three times

array([1302, 1662, 1962, 1299])

In [47]:
sales_set1_jan={123, 456, 456,678}
sales_set2_feb={1110, 4560, 407,670}
sales_set3_mar={111, 460, 47,167}

In [54]:
a=np.array(sales_set1_jan)
b=np.array(sales_set2_feb)
c=np.array(sales_set3_mar)

In [50]:
type(np.array(sales_set2_feb))

numpy.ndarray

In [67]:
total_sales = a+b+c     #### problem question??

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [68]:
total_sales = sum(a+b+c)
print(total_sales)
            

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [70]:
sales_array=np.array(sales)

In [71]:
sales_array 

array([2343, 2334, 3434, 3433])

In [72]:
sales_array1=sales_array[0]=234300 ## we can change the parent aaray  by creating an subst and then making a change in that

In [73]:
sales_array1

234300

In [74]:
sales_array

array([234300,   2334,   3434,   3433])

In [ ]:
## matrix
## in numpy we also have range function which give us range like normal range function

In [79]:
a=np.arange(0, 20) # numpy range function(arange)

In [78]:
list(range(0,20))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [80]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [83]:
np.matrix(a(5,4))

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
### we can also change an array into a matric using np.reshape

In [84]:
np.reshape(a, (5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [88]:
np.reshape(a, (5,4),'c') ### 'c' will print the matrix column wise, which is default

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [89]:
np.reshape(a, (5,4), 'f')  ### 'f' will print the matrix row wise, which is default

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [92]:
## converting list into an array and then converting it into an array
sales_uk=[123,456,789, 890]  
sales_us=[125,450,7890, 8900]
sales_in=[12,45,7089, 8190]

In [97]:
sales_matrix = np.array([sales_uk, sales_us,sales_in])


In [98]:
profit_uk=[50,60,78, 89]
profit_us=[12,45,70, 80]
profit_in=[1,4.5,89, 81]

In [99]:
profit_matrix=np.array([profit_uk, profit_us,profit_in])

In [102]:
profitratio1= (profit_matrix/ sales_matrix)*100

In [103]:
profitratio1

array([[40.6504065 , 13.15789474,  9.88593156, 10.        ],
       [ 9.6       , 10.        ,  0.88719899,  0.8988764 ],
       [ 8.33333333, 10.        ,  1.25546622,  0.98901099]])

In [104]:
profitratio1.T ### this will transpose the matrix

array([[40.6504065 ,  9.6       ,  8.33333333],
       [13.15789474, 10.        , 10.        ],
       [ 9.88593156,  0.88719899,  1.25546622],
       [10.        ,  0.8988764 ,  0.98901099]])