# Regression Assignment

# Scenario 1- x, y both are increasing

In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
os.chdir(r'C:\Users\Consultant20162\Desktop\Python Certification\Datesets\Linear Regression Scenarios')

In [3]:
dataset=pd.read_excel('LR-1.xlsx')

In [4]:
dataset

experience  salary
0           1    1000
1           2    2000
2           3    3000
3           4    4000
4           5    5000
5           6    6000
6           7    7000
7           8    8000
8           9    9000
9          10   10000

In [5]:
x=dataset.iloc[:, 0:1].values

In [6]:
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]], dtype=int64)

In [7]:
y=dataset.iloc[:,-1].values

In [8]:
y

array([ 1000,  2000,  3000,  4000,  5000,  6000,  7000,  8000,  9000,
       10000], dtype=int64)

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=0)

In [12]:
len(x_train)

7

In [13]:
len(x_test)

3

In [15]:
from sklearn.linear_model import LinearRegression
linear_model=LinearRegression()
linear_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
y_pred=linear_model.predict(x_test)

In [17]:
y_pred

array([3000., 9000., 5000.])

In [19]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

1.0

In [20]:
linear_model.coef_

array([1000.])

In [21]:
linear_model.intercept_

9.094947017729282e-13

# salary=1000*exp + 9.09

# Scenario 2- x, y both are decreasing

In [70]:
os.chdir(r'C:\Users\Consultant20162\Desktop\Python Certification\Datesets\Linear Regression Scenarios')

In [87]:
dataset=pd.read_excel('LR-2.xlsx')

In [88]:
dataset

experience  salary
0          20  200000
1          18  180000
2          16  160000
3          14  140000
4          12  120000
5          10  100000
6           8   80000
7           6   60000
8           4   40000
9           2   20000

In [89]:
x=dataset.iloc[:,0:1].values

In [90]:
x

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]], dtype=int64)

In [91]:
y=dataset.iloc[:, -1].values

In [92]:
y

array([200000, 180000, 160000, 140000, 120000, 100000,  80000,  60000,
        40000,  20000], dtype=int64)

In [144]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=8)

In [145]:
len(x_train)

7

In [146]:

len(x_test)

3

In [147]:
from sklearn.linear_model import LinearRegression
liner_model = LinearRegression()
liner_model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [148]:
y_pred = liner_model.predict(x_test)

In [149]:
y_pred

array([ 876.14754098, 1145.55737705,  741.44262295])

In [150]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9273780063541616

# Scenario 3- x is increasing , y is decreasing

In [108]:
os.chdir(r'C:\Users\Consultant20162\Desktop\Python Certification\Datesets\Linear Regression Scenarios')

In [109]:
dataset=pd.read_excel('LR-3.xlsx')

In [110]:
dataset

experience  salary
0           2    2000
1           3    1800
2           4    1600
3           5    1578
4           6    1435
5           7    1300
6           8    1200
7           9    1000
8          10     800
9          11     750

In [113]:
x=dataset.iloc[:, 0:1].values

In [114]:
x

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]], dtype=int64)

In [117]:
y=dataset.iloc[:,-1].values

In [118]:
y

array([2000, 1800, 1600, 1578, 1435, 1300, 1200, 1000,  800,  750],
      dtype=int64)

In [130]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=3)

In [134]:
from sklearn.linear_model import LinearRegression
linear_model = LinearRegression()
linear_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [135]:
y_pred=linear_model.predict(x_test)

In [136]:
y_pred

array([1275.42857143, 1413.01680672, 1825.78151261])

In [137]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9869096852840028

In [138]:
linear_model.coef_

array([-137.58823529])

In [139]:
linear_model.intercept_

2238.546218487395

# salary=-137.58*exp+2238.54

# Scenario 4- x is increasing, y is constant

In [153]:
os.chdir(r'C:\Users\Consultant20162\Desktop\Python Certification\Datesets\Linear Regression Scenarios')

In [154]:
dataset=pd.read_excel('LR-4.xlsx')

In [155]:
dataset

exp  salary
0    2   10000
1    3   10000
2    4   10000
3    5   10000
4    6   10000
5    7   10000
6    8   10000
7    9   10000
8   10   10000
9   11   10000

In [158]:
x=dataset.iloc[:, 0:1].values

In [159]:
x

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]], dtype=int64)

In [160]:
y=dataset.iloc[:,-1].values

In [161]:
y

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000], dtype=int64)

In [170]:
from sklearn.model_selection import train_test_split
(x_train, x_test, y_train, y_test)=train_test_split(x, y, test_size=0.3, random_state=0)

In [171]:
from sklearn.linear_model import LinearRegression
linear_model=LinearRegression()
linear_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [172]:
y_pred= linear_model.predict(x_test)

In [173]:
y_pred

array([10000., 10000., 10000.])

In [174]:
from sklearn.metrics import r2_score
r2_score(y_pred, y_test)

1.0

In [175]:
linear_model.coef_

array([-0.])

In [176]:
linear_model.intercept_

10000.0

# salary=-0.* exp+10000

# Scenario 5- x is constant, y is decreasing

In [177]:
os.chdir(r'C:\Users\Consultant20162\Desktop\Python Certification\Datesets\Linear Regression Scenarios')

In [186]:
dataset=pd.read_excel('LR-5.xlsx')

In [187]:
dataset

exp  salary
0    2   15000
1    2    1000
2    2    9000
3    2    8000
4    2    7500
5    2    6000
6    2    5000
7    2    4000
8    2    3000
9    2    1000

In [188]:
x=dataset.iloc[:, 0:1].values

In [189]:
x

array([[2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2]], dtype=int64)

In [190]:
y=dataset.iloc[:,-1].values

In [191]:
y

array([15000,  1000,  9000,  8000,  7500,  6000,  5000,  4000,  3000,
        1000], dtype=int64)

In [195]:
from sklearn.model_selection import train_test_split
x_train,x_train, y_test, y_train=train_test_split(x, y, test_size=0.3, random_state=3)

In [196]:
from sklearn.linear_model import LinearRegression
linear_model= LinearRegression()
linear_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [197]:
y_pred=linear_model.predict(x_test)

In [198]:
y_pred

array([4833.33333333, 4833.33333333, 4833.33333333])

In [209]:
from sklearn.metrics import r2_score
r2_score(y_train, y_pred)

0.0

In [202]:
linear_model.coef_

array([0.])

In [204]:
linear_model.intercept_

4833.333333333333

# salary=0*exp+4833.33

# Scenario-6 when there are outliers

In [205]:
os.chdir(r'C:\Users\Consultant20162\Desktop\Python Certification\Datesets\Linear Regression Scenarios')

In [206]:
dataset=pd.read_excel('LR-6.xlsx')

In [207]:
dataset

exp  salary
0     4    7000
1     5    6000
2     6    8000
3     7    9000
4     8   10000
5     9   11000
6    10   12000
7    11   13000
8    12   14000
9    13    4000
10   14   30000

In [210]:
x=dataset.iloc[:, 0:1].values

In [211]:
y=dataset.iloc[:,-1].values

In [212]:
from sklearn.model_selection import train_test_split
x_train,x_train, y_test, y_train=train_test_split(x, y, test_size=0.3, random_state=3)

In [213]:
from sklearn.linear_model import LinearRegression
linear_model= LinearRegression()
linear_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [214]:
y_pred=linear_model.predict(x_test)

In [219]:
y_pred

array([ 5150., 12350.,  7550.])

In [229]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

ValueError: Found input variables with inconsistent numbers of samples: [7, 3]

In [228]:
liner_model.coef_

array([-134.70491803])

In [224]:
liner_model.intercept_

2223.1967213114754